area = ["Ang Mo Kio",
"Bedok",
"Bishan",
"Bukit Batok",
"Bukit Merah",
"Bukit Panjang",
"Bukit Timah",
"Choa Chu Kang",
"Clementi",
"Geylang",
"Hougang",
"Jurong East",
"Jurong West",
"Kallang",
"Marine Parade",
"Novena",
"Outram",
"Pasir Ris",
"Punggol",
"Queenstown",
"Sembawang",
"Sengkang",
"Serangoon",
"Tampines",
"Tanglin",
"Toa Payoh",
"Woodlands",
"Yishun",
"Others",
]

housing_type =[
    "1- and 2- Room Flats",
    "3-Room Flats",
    "4-Room Flats",
    "5-Room and Executive Flats",
    "Condominiums and Other Apartments",
    "Landed Properties",
]